# Generated by Django 5.2.16 on 2026-07-10 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='cvs/')),
                ('parsed_text', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.JSONField(blank=True, default=list)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date_posted', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('seniority_level', models.CharField(blank=True, max_length=50)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('sponsorship_flag', models.CharField(choices=[('SPONSORED', 'Sponsored'), ('NOT_MENTIONED', 'Not Mentioned'), ('NOT_SPONSORED', 'Not Sponsored')], default='NOT_MENTIONED', max_length=20)),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('match_reason', models.TextField(blank=True)),
                ('application_link', models.URLField(max_length=500)),
                ('tailored_pdf', models.FileField(blank=True, null=True, upload_to='tailored_cvs/')),
                ('processed', models.BooleanField(default=False)),
                ('search_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.searchrun')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_countries', models.JSONField(blank=True, default=list, help_text='List of target country names.')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the system default minimum salary when set.', max_digits=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User preferences',
                'verbose_name_plural': 'User preferences',
            },
        ),
    ]
