# Generated by Django 5.2.16 on 2026-07-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tailored_text',
            field=models.TextField(blank=True),
        ),
    ]
