# Generated by Django 5.2.16 on 2026-07-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_tailored_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrun',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
