# Generated by Django 5.2.16 on 2026-07-11 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_searchrun_error_message_searchrun_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['id'], 'verbose_name': 'CV', 'verbose_name_plural': 'CVs'},
        ),
        migrations.AddField(
            model_name='cv',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_runs', to='jobs.cv'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='currency',
            field=models.CharField(choices=[('GBP', '£ (GBP)'), ('USD', '$ (USD)'), ('EUR', '€ (EUR)')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='cv',
            name='original_file',
            field=models.FileField(blank=True, upload_to='cvs/'),
        ),
    ]
