# Generated by Django 5.2.16 on 2026-07-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_cv_options_cv_name_searchrun_cv_and_more'),
    ]

    operations = [
        # Rename (not drop) so existing minimum-salary values are preserved.
        migrations.RenameField(
            model_name='userpreferences',
            old_name='min_salary',
            new_name='salary_min',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum acceptable salary. Overrides the system default when set.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum acceptable salary (optional; blank = no upper limit).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='total_jobs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
