# Generated by Django 5.2.16 on 2026-07-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_userpreferences_min_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ats_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
