# Generated by Django 5.2.16 on 2026-07-12 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_ats_score_job_job_skills_job_missing_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ats_status',
            field=models.CharField(choices=[('NOT_CHECKED', 'Not checked'), ('PASSED', 'Passed'), ('BELOW_THRESHOLD', 'Below threshold'), ('REJECTED', 'ATS Rejected')], default='NOT_CHECKED', help_text='Outcome of the ATS check (phases 1 & 2 are hard filters).', max_length=20),
        ),
        migrations.CreateModel(
            name='ATSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField()),
                ('report_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_report', to='jobs.job')),
            ],
            options={
                'verbose_name': 'ATS report',
                'verbose_name_plural': 'ATS reports',
            },
        ),
    ]
