# Generated by Django 5.2.16 on 2026-07-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_ats_status_atsreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrun',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='target_city',
            field=models.CharField(blank=True, help_text='Optional city to narrow the search to. Blank searches the whole country.', max_length=100),
        ),
    ]
