# Generated by Django 5.2.16 on 2026-07-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_searchrun_city_userpreferences_target_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
