# Generated by Django 5.2.16 on 2026-07-13 19:49

from django.db import migrations, models


def clear_rejected_status(apps, schema_editor):
    """Retire the REJECTED status from rows written before rejection was removed.

    They are re-labelled BELOW_THRESHOLD, which is what they always really were:
    a CV that scored poorly against the job. Nothing is deleted — a job that was
    previously hidden behind an "ATS Rejected" badge is now simply a job with a
    score, which is the point of the change.
    """
    Job = apps.get_model('jobs', 'Job')
    Job.objects.filter(ats_status='REJECTED').update(ats_status='BELOW_THRESHOLD')


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_searchrun_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='above_salary_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(clear_rejected_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='job',
            name='ats_status',
            field=models.CharField(choices=[('NOT_CHECKED', 'Not checked'), ('PASSED', 'Passed'), ('BELOW_THRESHOLD', 'Below threshold')], default='NOT_CHECKED', help_text='Whether the tailored CV scored at or above the ATS threshold. Informational — it never withholds a job.', max_length=20),
        ),
    ]
